/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class TreRegex {
  constructor(pattern: string, ignoreCase?: boolean | undefined | null)
  test(text: string, options?: TreRegexOptions | undefined | null): boolean
  exec(text: string, options?: TreRegexOptions | undefined | null): TreRegexResult | null
  matchAll(text: string, options?: TreRegexOptions | undefined | null): Array<TreRegexResult>
}

export interface TreRegexErrors {
  insertions: number
  deletions: number
  substitutions: number
}

export interface TreRegexOptions {
  maxErrors?: number
  maxInsertions?: number
  maxDeletions?: number
  maxSubstitutions?: number
  maxCost?: number
  weightInsertion?: number
  weightDeletion?: number
  weightSubstitution?: number
}

export interface TreRegexResult {
  matchText: string
  submatches: Array<string | undefined | null>
  index: number
  endIndex: number
  cost: number
  errors: TreRegexErrors
}
